language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true # to upload artifacts created during the build
  dry-run: false
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^release@"